import { apiClient } from './axios';
import type { ApiResponse } from '@/types/api';
import type { ResourceApi } from './organization';
import { API_ENDPOINTS } from './endpoints';
import {
  drawingResponseSchema,
  drawingsResponseSchema,
  drawingRevisionResponseSchema,
  drawingRevisionsResponseSchema,
  exportOrdersResponseSchema,
  nextDrawingNumberResponseSchema,
  uploadedFileResponseSchema,
} from '@/types/exportOrders';
import type { ExportOrderFilters } from '@/types/exportOrders';

type ApiRecord = { id: string;[key: string]: unknown };

const unwrap = async <T>(request: Promise<{ data: ApiResponse<T> }>) => (await request).data.data;

type CrudEndpoints = { list: string; create: string; update?: (id: string) => string; remove?: (id: string) => string };

const crud = (paths: CrudEndpoints, options: { updateMethod?: 'put' | 'patch'; update?: boolean; remove?: boolean } = {}): ResourceApi<any> => ({
  list: (params) => unwrap(apiClient.get<ApiResponse<ApiRecord[]>>(paths.list, { params })),
  create: (data) => unwrap(apiClient.post<ApiResponse<ApiRecord>>(paths.create, data)),
 ...(options.update === false || !paths.update
  ? {}
  : {
      update: (id: string, data: Record<string, unknown>) =>
        options.updateMethod === 'patch'
          ? unwrap(
              apiClient.patch<ApiResponse<ApiRecord>>(
                paths.update!(id),
                data
              )
            )
          : unwrap(
              apiClient.put<ApiResponse<ApiRecord>>(
                paths.update!(id),
                data
              )
            ),
    }),
  ...(options.remove === false || !paths.remove ? {} : { remove: async (id: string) => { await apiClient.delete(paths.remove!(id)); } }),
});

export const hrmsApi = {
  employees: {
    ...crud(API_ENDPOINTS.hrms.employees),
    sync: () => apiClient.post("/employee/sync").then(res => res.data),
  },
  attendance: crud(API_ENDPOINTS.hrms.attendance), leave: crud(API_ENDPOINTS.hrms.leave),
  salary: crud(API_ENDPOINTS.hrms.salary), holidays: crud(API_ENDPOINTS.hrms.holidays),
  shifts: { list: () => apiClient.get(API_ENDPOINTS.hrms.shifts.list).then((res) => res.data.data) },
  documents: crud(API_ENDPOINTS.hrms.documents),
  tasks: {
    ...crud((API_ENDPOINTS.hrms as any).tasks, { updateMethod: 'patch' }),
    updateNotification: (id: string, data: any) => apiClient.patch(`/task/notification/settings/${id}`, data).then(res => res.data),
    sendReminders: () => apiClient.post("/task/notification/send-reminders").then(res => res.data)
  }
};

export const crmApi = {
  customers: {
    ...crud(API_ENDPOINTS.crm.customers),
    sync: () => apiClient.post(API_ENDPOINTS.crm.customers.sync).then(res => res.data),
  },

  communications: crud(
    API_ENDPOINTS.crm.communications,
    { update: false }
  ),

  leads: crud(API_ENDPOINTS.crm.leads),
};

export const tenderApi = {
  requests: crud(API_ENDPOINTS.tender.requests), tenders: crud(API_ENDPOINTS.tender.tenders),
  governmentDepartments: crud(API_ENDPOINTS.tender.governmentDepartments), sections: crud(API_ENDPOINTS.tender.sections),
  divisions: crud(API_ENDPOINTS.tender.divisions), subDivisions: crud(API_ENDPOINTS.tender.subDivisions),
  vendors: crud((API_ENDPOINTS.tender as any).vendors, { updateMethod: 'patch' }),
  vendorProducts: {
    list: (vendorId?: string) =>
      unwrap(apiClient.get<ApiResponse<any[]>>('/vendor-product/read', { params: vendorId ? { vendorId } : {} })),
      listByMaterial: (materialId: string) =>
    unwrap(
      apiClient.get<ApiResponse<any[]>>(
        "/vendor-product/read",
        {
          params: { materialId },
        },
      ),
    ),
    attach: (vendorId: string, materialIds: string[]) =>
      unwrap(apiClient.post<ApiResponse<any[]>>('/vendor-product/create', { vendorId, materialIds })),
    detach: (id: string) =>
      apiClient.delete(`/vendor-product/delete/${id}`).then(res => res.data),
  

  },
  technicalClarifications: {
    ...crud(API_ENDPOINTS.tender.technicalClarifications),
    read: (id: string) => unwrap(apiClient.get<ApiResponse<any>>(`/technical-clarification/read/${id}`)),
    reply: (id: string, data: { reply: string; repliedById?: string; isInternal?: boolean }) => unwrap(apiClient.post<ApiResponse<any>>(`/technical-clarification/reply/${id}`, data)),
    addAttachment: (id: string, data: { fileName: string; fileUrl: string; fileSize?: number; mimeType?: string; uploadedById?: string }) => unwrap(apiClient.post<ApiResponse<any>>(`/technical-clarification/attachment/${id}`, data)),
  },
  boqs: crud(API_ENDPOINTS.tender.boqs),
  referenceCodes: {
    list: () => unwrap(apiClient.get<ApiResponse<ApiRecord[]>>(API_ENDPOINTS.tender.referenceCodes.list)),
    create: async () => { throw new Error('Reference codes are generated by the backend.'); },
  } satisfies ResourceApi<any>,
};

export const quotationApi = {
  quotations: {
    ...crud(API_ENDPOINTS.quotation.quotations),
    read: (id: string) => unwrap(apiClient.get<ApiResponse<any>>(`/quotation/read/${id}`)),
    submit: (id: string) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.submit(id), {})),
    send: (id: string) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.send(id), {})),
    respond: (id: string, data: { response: string; remarks?: string }) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.respond(id), data)),
    revise: (id: string, data: any) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.revise(id), data)),
  },
  items: crud(API_ENDPOINTS.quotation.items),
  approvals: crud(API_ENDPOINTS.quotation.approvals),
  activities: crud(API_ENDPOINTS.quotation.activities, { update: false }),
};

export const salesOrderApi = {
  salesOrders: {
    ...crud(API_ENDPOINTS.salesOrder.salesOrders),
    assign: (
      id: string,
      payload: {
        assignments: Array<{
          stage?: string | null;
          remarks?: string | null;
          userIds: string[];
        }>;
      },
    ) =>
      apiClient
        .put(API_ENDPOINTS.salesOrder.salesOrders.assign(id), payload)
        .then((res) => res.data),
    assignLegacy: (id: string, userIds: string[]) =>
      apiClient
        .put(API_ENDPOINTS.salesOrder.salesOrders.assign(id), { userIds })
        .then((res) => res.data),
  },
};

export const approvalRuleApi = {
  approvalRules: crud(API_ENDPOINTS.approvalRule.approvalRules),
};

export const securityApi = {
  users: {
    ...crud(API_ENDPOINTS.security.users),
    bulkImport: (file: File) => {
      const formData = new FormData();
      formData.append("file", file);
      return apiClient.post((API_ENDPOINTS.security.users as any).bulkImport, formData, {
        headers: { "Content-Type": "multipart/form-data" }
      }).then(res => res.data);
    }
  },
  roles: crud(API_ENDPOINTS.security.roles),
  settings: {
    read: () => apiClient.get(API_ENDPOINTS.security.settings.read).then(res => res.data.data),
    update: (data: any) => apiClient.post(API_ENDPOINTS.security.settings.update, data).then(res => res.data.data),
    testSmtp: (data: any) => apiClient.post((API_ENDPOINTS.security.settings as any).testSmtp, data).then(res => res.data),
    sendTestEmail: (data: any) => apiClient.post((API_ENDPOINTS.security.settings as any).sendTestEmail, data).then(res => res.data),
    sendPoEmail: (data: any) => apiClient.post((API_ENDPOINTS.security.settings as any).sendPoEmail, data).then(res => res.data),
    testWhatsapp: (data: any) => apiClient.post((API_ENDPOINTS.security.settings as any).testWhatsapp, data).then(res => res.data),
    exportBackup: () => apiClient.get((API_ENDPOINTS.security.settings as any).exportBackup).then(res => res.data.data),
    importBackup: (data: any) => apiClient.post((API_ENDPOINTS.security.settings as any).importBackup, data).then(res => res.data),
  },
  auditLogs: {
    list: () => apiClient.get((API_ENDPOINTS.security as any).auditLogs.list).then(res => res.data.data),
  }
};

export const workflowApi = {
  approvalRequests: crud((API_ENDPOINTS as any).workflow.approvalRequests),
};

export const materialApi = {
  materials: crud((API_ENDPOINTS as any).material.materials),
  categories: crud((API_ENDPOINTS as any).material.categories),
  brands: crud((API_ENDPOINTS as any).material.brands),
  specifications: crud((API_ENDPOINTS as any).material.specifications),
};

export const purchaseApi = {
  requests: crud((API_ENDPOINTS as any).purchase.requests),
  orders: crud((API_ENDPOINTS as any).purchase.orders, { updateMethod: 'patch' }),
  receipts: crud((API_ENDPOINTS as any).purchase.receipts),
};

export const inventoryApi = {
  warehouses: crud((API_ENDPOINTS as any).inventory.warehouses),
  bins: crud((API_ENDPOINTS as any).inventory.bins),
  stocks: crud((API_ENDPOINTS as any).inventory.stocks),
  transfers: crud((API_ENDPOINTS as any).inventory.transfers),
  list: () => apiClient.get('/inventory/read').then(res => res.data.data as any[]), // <-- ADD THIS
};

export const productionApi = {
  plans: crud((API_ENDPOINTS as any).production.plans),
  workOrders: crud((API_ENDPOINTS as any).production.workOrders),
  logs: crud((API_ENDPOINTS as any).production.logs),
};

export const qualityApi = {
  inspections: crud((API_ENDPOINTS as any).quality.inspections),
  reworks: crud((API_ENDPOINTS as any).quality.reworks),
};

export const logisticsApi = {
  dispatches: crud((API_ENDPOINTS as any).logistics.dispatches),
  vehicles: crud((API_ENDPOINTS as any).logistics.vehicles),
};

export const reportsApi = {
  getReport: (type: string, fromDate?: string, toDate?: string) =>
    apiClient.get(`/reports/read`, { params: { type, fromDate, toDate } }).then(res => res.data)
};

// Finance Payment API (used by Finance Manager pages)
export const financePaymentApi = {
  // Fetch all orders with received/balance totals for the main table
  getOrders: (params?: { search?: string; status?: string; page?: number; limit?: number }) =>
    apiClient.get("/payment/read/orders", { params }).then(res => res.data),

  // Fetch payment history for a specific sales order
  getPayments: (salesOrderId: string) =>
    apiClient.get("/payment/read/", { params: { salesOrderId } }).then(res => res.data),

  // Record a new installment payment
  createPayment: (data: {
    salesOrderId: string;
    amount: number;
    paymentMethod: string;
    referenceNo?: string;
    paymentDate?: string;
    remarks?: string;
  }) => apiClient.post("/payment/create/", data).then(res => res.data),

  // Update an existing payment
  updatePayment: (id: string, data: {
    amount?: number;
    paymentMethod?: string;
    referenceNo?: string;
    paymentDate?: string;
    remarks?: string;
  }) => apiClient.put(`/payment/update/${id}`, data).then(res => res.data),

  // Delete (soft-revert) a payment
  deletePayment: (id: string) =>
    apiClient.delete(`/payment/delete/${id}`).then(res => res.data),
};

// Export Orders API
export const exportOrdersApi = {
  // List sales orders with optional filters
  listOrders: (params?: ExportOrderFilters) =>
    apiClient.get(API_ENDPOINTS.exportOrders.list, { params })
      .then((res) => exportOrdersResponseSchema.parse(res.data)),

  // Fetch all drawings associated with given sales order IDs
  listDrawings: (orderIds: string[]) =>
    apiClient
      .get(API_ENDPOINTS.exportOrders.drawings, { params: { orderIds: orderIds.join(',') } })
      .then((res) => drawingsResponseSchema.parse(res.data)),

  // Get the next auto-incremented drawing number (e.g. DWG-004)
  nextDrawingNo: () =>
    apiClient.get(API_ENDPOINTS.exportOrders.nextDrawingNo)
      .then((res) => nextDrawingNumberResponseSchema.parse(res.data)),

  // Create a drawing record, automatically linking/creating the project for the given sales order
  createDrawing: (data: {
    salesOrderId: string;
    drawingNo: string;
    title: string;
    drawingType: string;
    fileUrl: string;
    fileName: string;
    fileSize?: number | null;
    mimeType?: string | null;
  }) => apiClient.post(API_ENDPOINTS.exportOrders.createDrawing, data)
    .then((res) => drawingResponseSchema.parse(res.data)),

  // Create a new revision for an existing drawing (R1, R2, R3, ...)
  createDrawingRevision: (data: {
    drawingId: string;
    revisionNo?: number;
    fileUrl: string;
    fileName: string;
    fileSize?: number | null;
    mimeType?: string | null;
    changes?: string | null;
  }) =>
    apiClient
      .post(
        API_ENDPOINTS.exportOrders.createDrawingRevision(data.drawingId),
        {
          fileUrl: data.fileUrl,
          fileName: data.fileName,
          fileSize: data.fileSize,
          mimeType: data.mimeType,
          changes: data.changes,
        },
      )
      .then((res) => drawingResponseSchema.parse(res.data)),

  // Get complete revision history for a drawing
  listDrawingRevisions: (drawingId: string) =>
    apiClient
      .get(
        API_ENDPOINTS.exportOrders.listDrawingRevisions(drawingId),
      )
      .then((res) => drawingRevisionsResponseSchema.parse(res.data)),

  // Update the status of a specific revision
  updateDrawingRevisionStatus: (
    revisionId: string,
    status: "SUBMITTED" | "APPROVED" | "REJECTED",
    rejectionReason?: string | null,
  ) =>
    apiClient
      .put(
        API_ENDPOINTS.exportOrders.updateDrawingRevisionStatus(revisionId),
        {
          status,
          rejectionReason,
        },
      )
      .then((res) => drawingRevisionResponseSchema.parse(res.data)),

  // Upload the drawing binary before creating its engineering-drawing record.
  uploadDrawingFile: (file: File) => {
    const formData = new FormData();
    formData.append('file', file);
    return apiClient.post('/upload/', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    }).then((res) => uploadedFileResponseSchema.parse(res.data));
  },

  updateDrawingStatus: (id: string, status: string, rejectionReason?: string | null) =>
    apiClient.put(API_ENDPOINTS.exportOrders.updateDrawing(id), { status, rejectionReason })
      .then((res) => drawingResponseSchema.parse(res.data)),

  deleteDrawing: (id: string) =>
    apiClient.delete(API_ENDPOINTS.exportOrders.deleteDrawing(id)).then((res) => res.data),

  // Send a drawing to a customer via Email/WhatsApp
  sendDrawing: (data: {
    drawingId: string;
    method: "EMAIL" | "WHATSAPP" | "BOTH";
    email?: string | null;
    phone?: string | null;
    subject?: string | null;
    message?: string | null;
  }) => apiClient.post(API_ENDPOINTS.exportOrders.sendDrawing, data)
    .then((res) => res.data),
};


